devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('account/', views.account_user, name='account'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.user_profile, name='user-profile'),
]

projects/models.py
from django.db import models

import uuid

from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True,blank=True,
                              on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True,
                                       default='default.jpg')
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title
    

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    # owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=255, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return self.name
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    short_intro = models.CharField(max_length=50, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True,
                                      upload_to='profiles/',
                                      default='profiles/user-default.png')
    social_github = models.CharField(max_length=255, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return str(self.user.username)
    

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE,
                              null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return str(self.name)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'email',
            'username',
            'password1',
            'password2',
        ]
        labels = {
            'first_name': 'Name'
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Profile
from .forms import CustomUserCreationForm


def login_user(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'Username or password is incorrect')

    return render(request, 'users/login-register.html', {'page': page})


def logout_user(request):
    messages.info(request, 'User was logged out')
    logout(request)
    return redirect('login')


def register_user(request):
    page = 'register'
    form = CustomUserCreationForm

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower().strip()
            user.save()

            messages.success(request, 'User account was created')

            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request,
                           'An error has occoured during registration')


    context = {'page': page, 'form': form}
    return render(request, 'users/login-register.html', context)


def profiles(request):
    profiles = Profile.objects.all()

    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)


def user_profile(request, pk):
    profile = Profile.objects.get(id=pk)

    top_skills = profile.skill_set.exclude(description__exact='')
    other_skills = profile.skill_set.filter(description='')

    context = {'profile': profile,
               'top_skills': top_skills,
               'other_skills': other_skills,}

    return render(request, 'users/user-profile.html', context)


@login_required(login_url='login')
def account_user(request):
    profile = request.user.profile

    context = {'profile': profile}
    return render(request, 'users/account.html', context)

users/templates/users/account.html
{% extends "main.html" %}

{% block content %}

<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{ profile.profile_image.url }}" />
            <h2 class="dev__name">{{ profile.name }}</h2>
            <p class="dev__title">{{ profile.short_intro }}</p>
            <p class="dev__location">Based in {{ profile.location }}</p>

            <ul class="dev__social">
              <li>
                <a title="Github" href="{{ profile.social_github }}" target="_blank">
                  <i class="im im-github"></i>
                  Github
                </a>
              </li>
            </ul>

          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{ profile.bio }}
          </p>
        </div>

        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">
          <tr>
            <td class="settings__tableInfo">
              <h4>JavaScript</h4>
              <p>
                Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                exercitationem fugiat?...
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          <tr>
            <td class="settings__tableInfo">
              <h4>Python</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est, suscipit...</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          <tr>
            <td class="settings__tableInfo">
              <h4>Django</h4>
              <p>
                Amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
                odio Est, suscipit...
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">
          <tr>
            <td class="settings__thumbnail">
              <a href="single-project.html"><img src="images/project-a.png" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="single-project.html">Yoga Studio Landing Page</a>
              <p>
                Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                exercitationem fugiat?...
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          <tr>
            <td class="settings__thumbnail">
              <a href="single-project.html"><img src="images/project-b.png" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="single-project.html">DevSearch Website UI Design</a>
              <p>
                Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                exercitationem fugiat?...
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          <tr>
            <td class="settings__thumbnail">
              <a href="single-project.html"><img src="images/project-a.png" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="single-project.html">Portfolio Website Design</a>
              <p>
                Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                exercitationem fugiat?...
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/login-register.html
{% extends "main.html" %}
{% load static %}

{% block content %}

{% if page == 'login' %}
<div class="auth">
    <div class="card">
    <div class="auth__header text-center">
        <a href="/">
        <img src="{% static "images/icon.svg" %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
    </div>


    <form action="{% url "login" %}" class="form auth__form" method="POST">
        {% csrf_token %}
        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>
    
        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
    </form>

    <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url "register" %}">Sign Up</a>
    </div>
    </div>
</div>

{% else %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static "images/icon.svg" %}" alt="icon" />
      </a>
      <h3>Account SignUp</h3>
      <p>Create a new developer account</p>
    </div>

    <form action="{% url "register" %}" class="form auth__form" method="POST">
      {% csrf_token %}
      <!-- Input:Text -->
      {% for field in form %}
      <div class="form__field">
        <label for="formInput#text">{{ field.label }}: </label>
        {{ field }}

        {% comment %} {% if field.help_text %}
        <small>{{ field.help_text }}</small>
        {% endif %} {% endcomment %}

        {% for error in field.errors %}
        
        <p style="color: red;">{{ error }}</p>

        {% endfor %} 

      {% endfor %}

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>

    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url "login" %}">Log In</a>
    </div>
  </div>
</div>

{% endif %}

{% endblock content %}

users/templates/users/profile.html
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img class="avatar avatar--xl" src="https://avatars.githubusercontent.com/u/33843378" />
            <h2 class="dev__name">Dennis Ivanov</h2>
            <p class="dev__title">Expirance FullStack Developer, Youtuber and Instructor</p>
            <p class="dev__location">Based in Florida, USA</p>
            <ul class="dev__social">
              <li>
                <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
              </li>
              <li>
                <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
              </li>
              <li>
                <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
              </li>
              <li>
                <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
              </li>
              <li>
                <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
              </li>
            </ul>
            <a href="#" class="btn btn--sub btn--lg">Send Message </a>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex illum ipsum iusto consequatur. Totam,
            dolorum fugiat, debitis facere illo nostrum nesciunt maxime, deserunt enim voluptatibus modi natus velit
            voluptatum. Dicta eritatis exercitationem ut quos a placeat obcaecati? Architecto illum!
            <br />
            Amet consectetur adipisicing elit. Veritatis exercitationem ut quos a placeat obcaecati? Architecto
            illum, atque delectus nemo dolorem inventore ab facilis? Dolor placeat vel delectus ipsam ullam.
          </p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            <div class="devSkill">
              <h4 class="devSkill__title">JavaScript</h4>
              <p class="devSkill__info">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae neque voluptatum ut? Quaerat, ea
                cumque! Dolorum provident esse molestias commodi odit sapiente quod quasi corrupti obcaecati? Nobis
                ex temporibus quaerat!
              </p>
            </div>
            <div class="devSkill">
              <h4 class="devSkill__title">React</h4>
              <p class="devSkill__info">
                Smet consectetur adipisicing elit. Omnis, nihil? Accusamus aspernatur aut debitis vitae quaerat
                nihil fugiat, doloremque nesciunt alias pariatur maxime unde, nam saepe laborum at odit labore.
              </p>
            </div>
            <div class="devSkill">
              <h4 class="devSkill__title">Express(Nodejs)</h4>
              <p class="devSkill__info">
                Auae error deleniti aperiam enim nisi nesciunt, ratione eveniet eos fuga ad recusandae mollitia!
                Facere earum, distinctio nihil recusandae ipsum nesciunt. Possimus, ex. Officia maxime nihil
                inventore cum tenetur! Veritatis sapiente libero ducimus nesciunt itaque, placeat inventore sint
                blanditiis?
              </p>
            </div>

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              <span class="tag tag--pill tag--sub tag--lg">
                <small>Figma</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>Vuejs</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>REST API</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>GraphQL</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>TypeScript</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>Webpack</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>NextJS</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>Postgres</small>
              </span>
              <span class="tag tag--pill tag--sub tag--lg">
                <small>MongoDB</small>
              </span>
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">

            <div class="column">
              <div class="card project">
                <a href="single-project.html" class="project">
                  <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                  <div class="card__body">
                    <h3 class="project__title">DevSearch UI Design</h3>
                    <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                    <p class="project--rating">
                      <span style="font-weight: bold;">92%</span> Postitive
                      Feedback (62 Votes)
                    </p>
                    <div class="project__tags">
                      <span class="tag tag--pill tag--main">
                        <small>NextJS</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>GraphQL</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>TypeScript</small>
                      </span>
                    </div>
                  </div>
                </a>
              </div>
            </div>

            <div class="column">
              <div class="card project">
                <a href="single-project.html" class="project">
                  <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                  <div class="card__body">
                    <h3 class="project__title">Another Landing Page</h3>
                    <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                    <p class="project--rating">
                      <span style="font-weight: bold;">36%</span> Postitive
                      Feedback (18 Votes)
                    </p>
                    <div class="project__tags">
                      <span class="tag tag--pill tag--main">
                        <small>NextJS</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>GraphQL</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>TypeScript</small>
                      </span>
                    </div>
                  </div>
                </a>
              </div>
            </div>

            <div class="column">
              <div class="card project">
                <a href="single-project.html" class="project">
                  <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                  <div class="card__body">
                    <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                    <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                    <p class="project--rating">
                      <span style="font-weight: bold;">98%</span> Postitive
                      Feedback (72 Votes)
                    </p>
                    <div class="project__tags">
                      <span class="tag tag--pill tag--main">
                        <small>NextJS</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>GraphQL</small>
                      </span>
                      <span class="tag tag--pill tag--main">
                        <small>TypeScript</small>
                      </span>
                    </div>
                  </div>
                </a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

users/templates/users/profiles.html
{% extends "main.html" %}

{% block content %}

<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
        <div class="hero-section__box">
            <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
            <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
            <form class="form" action="#" method="get">
            <div class="form__field">
                <label for="formInput#search">Search Developers </label>
                <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
            </form>
        </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
        <div class="grid grid--three">

            {% for profile in profiles %}
            <div class="column card">
                <div class="dev">
                    <a href="{% url "user-profile" profile.id %}" class="card__body">
                    <div class="dev__profile">
                        <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                        <div class="dev__meta">
                        <h3>{{ profile.name }}</h3>
                        <h5>{{ profile.short_intro|slice:"60" }}</h5>
                        </div>
                    </div>
                    <p class="dev__info">
                        {{ profile.bio|slice:"150" }}
                    </p>

                    <div class="dev__skills">
                        {% for skill in profile.skill_set.all|slice:'3' %}
                        <span class="tag tag--pill tag--main">
                        <small>{{ skill }}</small>
                        </span>
                        {% endfor %}
                    </div>


                    </a>
                </div>
            </div>
            {% endfor %}

        </div>
        </div>
    </section>
</main>

{% endblock content %}

users/templates/users/user-profile.html
{% extends "main.html" %}

{% block content %}

<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                <div class="card__body dev">
                    <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                    <h2 class="dev__name">{{ profile.name }}</h2>
                    <p class="dev__title">{{ profile.short_intro }}</p>
                    <p class="dev__location">Based in {{ profile.location }}</p>

                    <ul class="dev__social">
                    {% if profile.social_github %}
                    <li>
                        <a title="Github" href="#" target="_blank">
                            <i class="im im-github"></i>
                            Github
                        </a>
                    </li>
                    {% endif %}
                    </ul>

                    <a href="#" class="btn btn--sub btn--lg">Send Message </a>
                </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                <h3 class="devInfo__title">About Me</h3>
                <p class="devInfo__about">
                    {{ profile.bio }}
                </p>
                </div>
                <div class="devInfo">
                <h3 class="devInfo__title">Skills</h3>
                <div class="devInfo__skills">

                    {% for top_skill in top_skills %}
                    <div class="devSkill">
                        <h4 class="devSkill__title">{{ top_skill.name }}</h4>
                        <p class="devSkill__info">
                            {{ top_skill.description }}
                        </p>
                    </div>
                    {% endfor %}

                    <h3 class="devInfo__subtitle">Other Skills</h3>

                    <div class="devInfo__otherSkills">
                    {% for other_skill in other_skills %}
                    <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{ other_skill }}</small>
                    </span>
                    {% endfor %}
                    </div>


                </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>

                    <div class="grid grid--two">
                        {% for project in profile.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url "project" project.id %}" class="project">
                                <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                                <div class="card__body">
                                    <h3 class="project__title">{{ project.name }}</h3>
                                    <p><a class="project__author" href="profile.html">By {{ project.owner.name }}</a></p>
                                    <p class="project--rating">
                                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span>
                                    Postitive Feedback ({{ project.vote_total }}) vote{{ project.vote_total|pluralize:'s' }}
                                    </p>

                                    <div class="project__tags">
                                        {% for tag in project.tags.all %}
                                        <span class="tag tag--pill tag--main">
                                            <small>{{ tag }}</small>
                                        </span>
                                        {% endfor %}
                                    </div>

                                </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}